/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.Global;
import java.applet.AudioClip;
import java.awt.CardLayout;
import javax.swing.ImageIcon;


/**
 *
 * @author Steven Paul Valdiviezo
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        bntStop = new javax.swing.JButton();
        bntPlay = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btLibros = new javax.swing.JButton();
        btFacturas = new javax.swing.JButton();
        btClientes = new javax.swing.JButton();
        lbFondoMenu = new javax.swing.JLabel();
        panelPie = new javax.swing.JPanel();
        lbCopy = new javax.swing.JLabel();
        lbMensaje = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Ventas de Libros");
        setBounds(new java.awt.Rectangle(200, 240, 1648, 900));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelMenu.setPreferredSize(new java.awt.Dimension(250, 274));
        panelMenu.setVerifyInputWhenFocusTarget(false);
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntStop.setBackground(new java.awt.Color(102, 51, 0));
        bntStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-de-pausa (1).png"))); // NOI18N
        bntStop.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boton-de-pausa.png"))); // NOI18N
        bntStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntStopActionPerformed(evt);
            }
        });
        panelMenu.add(bntStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 30, 30));

        bntPlay.setBackground(new java.awt.Color(102, 51, 0));
        bntPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/boton-de-play (2).png"))); // NOI18N
        bntPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/boton-de-play (1).png"))); // NOI18N
        bntPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPlayActionPerformed(evt);
            }
        });
        panelMenu.add(bntPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 30, 30));

        btHome.setBackground(new java.awt.Color(102, 51, 0));
        btHome.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btHome.setForeground(new java.awt.Color(255, 255, 255));
        btHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo_ConFondo.png"))); // NOI18N
        btHome.setBorder(null);
        btHome.setContentAreaFilled(false);
        btHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo_ConFondo.png"))); // NOI18N
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        panelMenu.add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-libro-64.png"))); // NOI18N
        panelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-factura-64.png"))); // NOI18N
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icons8-cliente-64.png"))); // NOI18N
        panelMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 80));

        btLibros.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btLibros.setForeground(new java.awt.Color(255, 255, 255));
        btLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe.png"))); // NOI18N
        btLibros.setText("Libros");
        btLibros.setBorder(null);
        btLibros.setContentAreaFilled(false);
        btLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLibros.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe_Claro.png"))); // NOI18N
        btLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLibrosActionPerformed(evt);
            }
        });
        panelMenu.add(btLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 50));

        btFacturas.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe.png"))); // NOI18N
        btFacturas.setText("Facturas");
        btFacturas.setBorder(null);
        btFacturas.setContentAreaFilled(false);
        btFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFacturas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe_Claro.png"))); // NOI18N
        btFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFacturasActionPerformed(evt);
            }
        });
        panelMenu.add(btFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, 50));

        btClientes.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btClientes.setForeground(new java.awt.Color(255, 255, 255));
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorder(null);
        btClientes.setContentAreaFilled(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/BotonCafe_Claro.png"))); // NOI18N
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        panelMenu.add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 50));

        lbFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_3_Madera.jpg"))); // NOI18N
        panelMenu.add(lbFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 250, 810));

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelPie.setBackground(new java.awt.Color(73, 31, 0));
        panelPie.setPreferredSize(new java.awt.Dimension(100, 40));
        panelPie.setLayout(new java.awt.BorderLayout());

        lbCopy.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lbCopy.setForeground(new java.awt.Color(255, 255, 255));
        lbCopy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCopy.setText("Copyright 2024 UTMACH");
        lbCopy.setToolTipText("");
        lbCopy.setPreferredSize(new java.awt.Dimension(250, 16));
        panelPie.add(lbCopy, java.awt.BorderLayout.LINE_START);

        lbMensaje.setBackground(new java.awt.Color(135, 68, 33));
        lbMensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lbMensaje.setText(" Mensaje de prueba");
        lbMensaje.setOpaque(true);
        panelPie.add(lbMensaje, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelPie, java.awt.BorderLayout.PAGE_END);

        panelCentral.setLayout(new java.awt.CardLayout());

        panelFondo.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo_1.jpg"))); // NOI18N
        panelFondo.add(jLabel1, java.awt.BorderLayout.LINE_START);

        panelCentral.add(panelFondo, "Fondo");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Clientes");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btClientesActionPerformed

    private void btFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFacturasActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Facturas");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btFacturasActionPerformed

    private void btLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLibrosActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Libros");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btLibrosActionPerformed

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
         try{
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "Fondo");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_btHomeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String path=Global.getPath();
        //Icono de la aplicación
        ImageIcon icon = new ImageIcon(path+ "\\Recursos\\Icono.png");
        setIconImage(icon.getImage());  
        setExtendedState(this.getExtendedState() | frmPrincipal.MAXIMIZED_BOTH); //maximizar
        //agregar todos los paneles creados
        panelCentral.add(new panelClientes(),"Clientes");
        panelCentral.add(new panelLibros(),"Libros");
        panelCentral.add(new panelFacturas(),"Facturas");
    }//GEN-LAST:event_formWindowActivated

    private void bntPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPlayActionPerformed
        AudioClip Sound;
        Sound = java. applet. Applet.newAudioClip(getClass().getResource("/recursos/Musica_Fondo"));
        Sound.play();
    }//GEN-LAST:event_bntPlayActionPerformed

    private void bntStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntStopActionPerformed
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/recursos/Musica_Fondo"));
        Sound.stop();
    }//GEN-LAST:event_bntStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPlay;
    private javax.swing.JButton bntStop;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btFacturas;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbCopy;
    private javax.swing.JLabel lbFondoMenu;
    public static javax.swing.JLabel lbMensaje;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPie;
    // End of variables declaration//GEN-END:variables
}
